Sprint 09
nickyTOSSter/ImageFeed pull request #2
Opened 2023-02-26 08:48 UTC by nickyTOSSter

2023-02-26 21:37 UTC, mmbabaev requested changes

2023-02-26 21:37 UTC, mmbabaev commented on ImageFeed/ImagesList/ImageListViewController.swift
> +    private let currentDateFormatted = Date().formatted
сейчас это ни на что не влияет, но лучше так не сохранять дату, а создавать ее динамически во время использования

2023-02-26 21:37 UTC, mmbabaev commented on ImageFeed/ImagesList/ImageListViewController.swift
> +            super.prepare(for: segue, sender: sender)
возможно лучше вызывать всегда super. Хотя насколько я знаю, он ничего не делает в базовом классе

2023-02-26 21:37 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListCell.swift
> +    @IBOutlet weak var cellImage: UIImageView!
стоит добавить private, чтобы свойства не были видны снаружи

2023-02-26 21:37 UTC, mmbabaev commented on ImageFeed/Profile/ProfileViewController.swift
> +    private var avatarImageView: UIImageView!
Можно создавать черезз lazy:
```
lazy var label: UILabel {
   let label = UILabel()
   //
   return label
}
```

2023-02-26 21:37 UTC, mmbabaev commented on ImageFeed/Profile/ProfileViewController.swift
> +    // In a storyboard-based application, you will often want to do a little preparation before navigation
это лучше удалять

2023-02-26 21:37 UTC, mmbabaev commented on ImageFeed/SingleImageView/SingleImageViewController.swift
> +    var image: UIImage! {
лучше заменить на ? опционал

2023-02-26 21:37 UTC, mmbabaev commented on ImageFeed/SingleImageView/SingleImageViewController.swift
> +    @IBOutlet weak var scrollView: UIScrollView!
private

2023-02-26 21:37 UTC, mmbabaev commented on ImageFeed/SingleImageView/SingleImageViewController.swift
> +        let activity = UIActivityViewController(activityItems: [image], applicationActivities: nil)
здесь ворнинг, уйдет с опционалом ? и разворачиваем картинки в guard let

2023-02-26 21:37 UTC, mmbabaev commented on ImageFeed/SingleImageView/SingleImageViewController.swift
> +    var image: UIImage! {
Также в этом контроллере падает приложение, картинки нет

2023-02-26 21:37 UTC, mmbabaev commented on ImageFeed/SingleImageView/SingleImageViewController.swift
> +    var image: UIImage! {
<img width="221" alt="Screenshot 2023-02-27 at 00 35 19" src="https://user-images.githubusercontent.com/12600807/221438772-9e019924-b410-40fa-be69-c69d26977ddf.png">
создаются картинки с "full_size", такая только первая

2023-02-28 17:21 UTC, nickyTOSSter commented on ImageFeed/ImagesList/ImagesListCell.swift
> +    @IBOutlet weak var cellImage: UIImageView!
Свойство используется в ImageListViewController при получении ячейки

2023-02-28 17:27 UTC, nickyTOSSter commented on ImageFeed/Profile/ProfileViewController.swift
> +    private var avatarImageView: UIImageView!
Не понял для чего тут lazy. Насколько понимаю lazy используем если собираемся инициализировать что-то "тяжелое". Если это возможно можно подробнее?

2023-02-28 18:19 UTC, nickyTOSSter commented on ImageFeed/SingleImageView/SingleImageViewController.swift
> +    var image: UIImage! {
картинки добавлять не стал
сделал метод возвращающий картину - full size если есть и обычную если нет

2023-03-01 14:05 UTC, merged